export const dashboardCards = [
    {
        id: 1,
        icon: 'fa-shield-alt',
        title: 'Incidentes de Seguridad',
        subtitle: '1 Incidente Registrado',
        linkText: 'Ver incidentes',
        linkPath: '/incidentes',
    },
    {
        id: 2,
        icon: 'fa-tools',
        title: 'Solicitudes de Mantenimiento',
        subtitle: '8 Pendientes',
        linkText: 'Ver todas las solicitudes',
        linkPath: '/mantenimiento',
    },
    {
        id: 3,
        icon: 'fa-user',
        title: 'Visitas Recientes',
        subtitle: '3 Autorizados',
        linkText: 'Ver detalles de acceso',
        linkPath: '/visitas',
    },
    {
        id: 4,
        icon: 'fa-file-alt',
        title: 'Boletas de Pago Subidas',
        subtitle: '10 Nuevas',
        linkText: 'Ver todas las boletas',
        linkPath: '/boletas',
    },
    {
        id: 5,
        icon: 'fa-envelope',
        title: 'Correspondencia Recibida',
        subtitle: '2 Paquetes',
        linkText: 'Ver toda la correspondencia',
        linkPath: '/correspondencia',
    },
    {
        id: 6,
        icon: 'fa-calendar-alt',
        title: 'Reservas Próximas',
        subtitle: '5 Áreas Comunes Reservadas',
        linkText: 'Gestionar reservas',
        linkPath: '/reservas',
    },
    {
        id: 7,
        icon: 'fa-calendar',
        title: 'Eventos del Condominio',
        subtitle: '2 Próximos',
        linkText: 'Ver eventos',
        linkPath: '/eventos',
    },
];
